baseURL = "https://priyavr.at"
title = "Priyavrat Misra"
languageCode = "en-us"
theme = "devise-improved"
relativeURLs = false
enableEmoji = false
enableRobotsTXT = true
enableGitInfo = true
pluralizelisttitles = false
copyright = "&copy; 2022-{year} Priyavrat Misra.<br><em>This site is built on fundamentals and handcrafted for <abbr title='accessibility'>a11y</abbr>.</em>"

[taxonomies]
  tag = "tags"

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    title = "Ramblings for the curious mind."
    url = "/blog/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    title = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "resume"
    name = "Résumé"
    title = "Résumé"
    url = "/resume/"
    weight = 3

# Configuration Features
[params]
  header_title = "Priyavrat Misra"
  header_subtitle = "['Software Engineer', 'Computer Science Graduate', 'Open Source Advocate', 'Cycling Enthusiast']"
  description = "Priyavrat's corner of the internet."
  avatar = "avatar/120x120.webp"
  avatar_2x = "avatar/180x180.webp"
  knowsAbout = ["Software Engineering", "Distributed Systems", "Open Source", "Web Development"]
  math = false
  [[params.social]]
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/priyavrat-misra/"
    icon = "/icons/linkedin.svg"
  
  [[params.social]]
    title = "GitHub" 
    url = "https://github.com/priyavrat-misra"
    icon = "/icons/github.svg"
      
  [[params.social]]
    title = "Strava"
    url = "https://www.strava.com/athletes/priyavrat"
    icon = "/icons/activity.svg"
      
  [[params.social]]
    title = "Email"
    url = "mailto:misra.priyavrat@gmail.com"
    icon = "/icons/mail.svg"
      
  [[params.social]]
    title = "RSS Feed"
    url = "/blog/rss.xml"
    icon = "/icons/rss.svg"

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
  [markup.highlight]
    style = 'github-dark'
    